#ifndef DRIVER_UART_H_
#define DRIVER_UART_H_

/*******************************************************************************
 * Includes
 ******************************************************************************/
#include "MKE16Z4.h"  /* Microcontroller-specific definitions */

/*******************************************************************************
 * Definitions
 ******************************************************************************/
#define SystemCoreClock    48000000    /**< System core clock frequency in Hz */
#define BaudRate_UART      9600        /**< UART baud rate */

/*******************************************************************************
 * Function Prototypes
 ******************************************************************************/

/**
 * @brief  Initializes UART0 with the specified baud rate.
 *
 * @note   This function configures the UART0 settings, including the baud rate,
 *         based on the system core clock and predefined baud rate.
 */
void initUART0(void);

/**
 * @brief  Sends a single character over UART0.
 *
 * @param  data: The 8-bit character to be transmitted.
 *
 * @note   This function blocks until the character is successfully transmitted.
 */
void UART0_SendChar(uint8_t data);

/**
 * @brief  Sends a null-terminated string over UART0.
 *
 * @param  str: Pointer to the null-terminated string to be transmitted.
 *
 * @note   This function sends characters sequentially until the null terminator is reached.
 */
void UART0_SendString(uint8_t *str);


/**
 * @brief  UART0 interrupt handler.
 *
 * @note   This function handles interrupts generated by UART0, including
 *         transmit and receive operations.
 */
void LPUART0_IRQHandler(void);

#endif /* DRIVER_UART_H_ */

/*******************************************************************************
 * EOF
 ******************************************************************************/
